### ISSUE TITLE
Enhance error reporting/message

### ISSUE THREAD

**Issue by carlosmmatos** [opencontrol/compliance-masonry#373]
`standard_key: NIST-800-103` instead of `NIST-800-53` in file caused the following output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13f28ee]

goroutine 1 [running]:
github.com/opencontrol/compliance-masonry/validate.validateComponent(0x154d500, 0xc000097c80, 0x154d5c0, 0xc00165c000, 0x0, 0x0, 0x0)
        /Users/cmatos/training/gowork/src/github.com/opencontrol/compliance-masonry/validate/validate.go:43 +0x22e
github.com/opencontrol/compliance-masonry/validate.Validate()
        /Users/cmatos/training/gowork/src/github.com/opencontrol/compliance-masonry/validate/validate.go:19 +0x12a
github.com/opencontrol/compliance-masonry/pkg/cli/validate.NewCmdValidate.func1(0xc0001a4b00, 0x17e8c98, 0x0, 0x0)
        /Users/cmatos/training/gowork/src/github.com/opencontrol/compliance-masonry/pkg/cli/validate/validate.go:16 +0x25
github.com/opencontrol/compliance-masonry/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001a4b00, 0x17e8c98, 0x0, 0x0, 0xc0001a4b00, 0x17e8c98)
        /Users/cmatos/training/gowork/src/github.com/opencontrol/compliance-masonry/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/opencontrol/compliance-masonry/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000021340, 0xc000010010, 0x1541ae0, 0xc000010018)
        /Users/cmatos/training/gowork/src/github.com/opencontrol/compliance-masonry/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/opencontrol/compliance-masonry/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/cmatos/training/gowork/src/github.com/opencontrol/compliance-masonry/vendor/github.com/spf13/cobra/command.go:895
github.com/opencontrol/compliance-masonry/pkg/cmd/masonry.Run(0xffffffff, 0xc00008c058)
        /Users/cmatos/training/gowork/src/github.com/opencontrol/compliance-masonry/pkg/cmd/masonry/masonry.go:14 +0x74
main.main()
        /Users/cmatos/training/gowork/src/github.com/opencontrol/compliance-masonry/cmd/masonry/masonry.go:14 +0x25
```

none of which helped me find the issue of course lol.

**Comment by redhatrises** [comment]
@carlosmmatos wanna propose a fix?

**Comment by carlosmmatos** [comment]
yes - I just wanted to track it
